
name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt update -y -qq 
        sudo apt upgrade -y
        sudo apt-get install libsdl2-dev libsdl2-2.0-0 libsdl2-ttf-dev
    - name: make
      run: make
